Loading required package: MSeasy
Loading required package: amap
Loading required package: clValid
Loading required package: cluster
Loading required package: fpc
Loading required package: mzR
Loading required package: Rcpp
Loading required package: methods
Loading required package: xcms
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, cbind, colnames, do.call, duplicated, eval, evalq,
    get, grep, grepl, intersect, is.unsorted, lapply, lengths, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, rank,
    rbind, rownames, sapply, setdiff, sort, table, tapply, union,
    unique, unsplit, which, which.max, which.min

Loading required package: ProtGenerics
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

/jobfs/local/pbs/mom_priv/jobs/8664179.r-man2.SC: line 52: 17755 Killed                  Rscript instructions.R

======================================================================================
                  Resource Usage on 2018-07-24 13:48:31:
   Job Id:             8664179.r-man2
   Project:            ui08
   Exit Status:        137 (Linux Signal 9 SIGKILL Kill, unblockable)
   Service Units:      3.01
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 03:00:01                                   
   Memory Requested:   19.53GB               Memory Used: 1.27GB          
   Walltime requested: 03:00:00            Walltime Used: 03:00:24        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
