Loading required package: MSeasy
Loading required package: amap
Loading required package: clValid
Loading required package: cluster
Loading required package: fpc
Loading required package: mzR
Loading required package: Rcpp
Loading required package: methods
Loading required package: xcms
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, cbind, colnames, do.call, duplicated, eval, evalq,
    get, grep, grepl, intersect, is.unsorted, lapply, lengths, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, rank,
    rbind, rownames, sapply, setdiff, sort, table, tapply, union,
    unique, unsplit, which, which.max, which.min

Loading required package: ProtGenerics
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

[1] "cluster ok length= 52"
[1] "Your working directory is : /short/ui08/eg3324/mass_spec"
[1] "Text and pdf files have been generated in the folder: output_MSclust_resultThu_Jul_26_17-13-57"
[1] "Done"
Warning message:
NAs introduced by coercion 

======================================================================================
                  Resource Usage on 2018-07-26 17:15:14:
   Job Id:             8744826.r-man2
   Project:            ui08
   Exit Status:        0
   Service Units:      0.05
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 00:01:19                                   
   Memory Requested:   19.53GB               Memory Used: 95.52MB         
   Walltime requested: 01:00:00            Walltime Used: 00:02:52        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
